#!/usr/bin/env python3
"""
Syncs docs/typst-packages/ with the LICENSE and docs/ of typst/packages.

Compares upstream blob SHAs against local copies. If anything has changed,
writes the new content, commits to a branch, and opens (or updates) a PR
in this repo.  No fork or external repo writes — uses GITHUB_TOKEN only.
"""

import base64
import json
import os
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(
    subprocess.check_output(["git", "rev-parse", "--show-toplevel"], text=True).strip()
)
LOCAL_DIR = REPO_ROOT / "docs" / "typst-packages"
PR_BRANCH = "sync/upstream-typst-packages-docs"
UPSTREAM_REPO = "typst/packages"


def run(cmd: list[str], **kwargs) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, check=True, text=True, **kwargs)


def run_out(cmd: list[str]) -> str:
    return subprocess.check_output(cmd, text=True).strip()


def gh(*args: str) -> str:
    return run_out(["gh", "api"] + list(args))


def main() -> None:
    # 1. Fetch the full recursive tree from upstream
    tree_json = gh(f"repos/{UPSTREAM_REPO}/git/trees/main?recursive=1")
    tree = json.loads(tree_json)["tree"]

    # Filter to docs/* and LICENSE only
    upstream_files: dict[str, str] = {
        entry["path"]: entry["sha"]
        for entry in tree
        if entry["type"] == "blob"
        and (entry["path"].startswith("docs/") or entry["path"] == "LICENSE")
    }

    # 2. Compute local blob SHAs for existing mirror files
    local_shas: dict[str, str] = {}
    if LOCAL_DIR.exists():
        for local_file in LOCAL_DIR.rglob("*"):
            if local_file.is_file():
                rel = str(local_file.relative_to(LOCAL_DIR))
                sha = run_out(["git", "hash-object", str(local_file)])
                local_shas[rel] = sha

    # 3. Identify changed (new or modified) files
    changed = {
        path: sha
        for path, sha in upstream_files.items()
        if local_shas.get(path) != sha
    }

    if not changed:
        print("docs/typst-packages/ is already in sync with upstream.")
        return

    print(f"{len(changed)} file(s) changed upstream:")
    for p in sorted(changed):
        status = "new" if p not in local_shas else "modified"
        print(f"  [{status}] {p}")

    # 4. Fetch and write changed files
    for upstream_path in changed:
        content_data = json.loads(gh(f"repos/{UPSTREAM_REPO}/contents/{upstream_path}"))
        content = base64.b64decode(content_data["content"])
        local_path = LOCAL_DIR / upstream_path
        local_path.parent.mkdir(parents=True, exist_ok=True)
        local_path.write_bytes(content)
        print(f"  Written: {local_path.relative_to(REPO_ROOT)}")

    # 5. Check whether a sync PR already exists
    existing_pr = ""
    try:
        prs = json.loads(
            gh(f"repos/chaoticgoodcomputing/cgc-typst-packages/pulls"
               f"?head=chaoticgoodcomputing:{PR_BRANCH}&state=open")
        )
        if prs:
            existing_pr = prs[0]["html_url"]
    except Exception:
        pass

    # 6. Commit and push the sync branch
    os.chdir(REPO_ROOT)
    run(["git", "config", "user.email", "github-actions[bot]@users.noreply.github.com"])
    run(["git", "config", "user.name", "github-actions[bot]"])

    # Create (or reset) the branch on top of main
    run(["git", "checkout", "-B", PR_BRANCH, "origin/main"])

    run(["git", "add", "docs/typst-packages/"])
    run(["git", "commit", "-m", "chore: sync upstream typst/packages docs"])
    run(["git", "push", "--force-with-lease", "origin", PR_BRANCH])

    if existing_pr:
        print(f"::notice::Updated existing PR: {existing_pr}")
        return

    # 7. Open a new PR in this repo
    changed_list = "\n".join(f"- `{p}`" for p in sorted(changed))
    body = (
        "## Upstream changes detected\n\n"
        f"The following file(s) changed in `typst/packages`:\n\n{changed_list}\n\n"
        "---\n*Auto-generated by the sync-upstream-docs workflow.*"
    )
    run(
        [
            "gh", "pr", "create",
            "--title", "chore: sync upstream typst/packages docs",
            "--body",  body,
            "--head",  PR_BRANCH,
            "--base",  "main",
        ]
    )
    print("PR opened.")


if __name__ == "__main__":
    main()
