#!/usr/bin/env node
'use strict';

/**
 * Syncs docs/typst-packages/ with the LICENSE and docs/ of typst/packages.
 *
 * Compares upstream blob SHAs against local copies. If anything has changed,
 * writes the new content, commits to a branch, and opens (or updates) a PR
 * in this repo.  Uses GITHUB_TOKEN only — no external repo writes.
 */

const { spawnSync, execFileSync } = require('node:child_process');
const { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } = require('node:fs');
const path = require('node:path');

const UPSTREAM_REPO = 'typst/packages';
const THIS_REPO = 'chaoticgoodcomputing/cgc-typst-packages';
const PR_BRANCH = 'sync/upstream-typst-packages-docs';

// ── Helpers ───────────────────────────────────────────────────────────────────

function run(cmd, args, opts = {}) {
  const result = spawnSync(cmd, args, { encoding: 'utf8', ...opts });
  if (result.status !== 0) {
    console.error(`${cmd} ${args.join(' ')}\n${result.stderr}`);
    process.exit(1);
  }
  return result.stdout.trim();
}

function git(...args) {
  return run('git', args);
}

function gh(...args) {
  return run('gh', args, { maxBuffer: 16 * 1024 * 1024 });
}

function ghJson(...args) {
  return JSON.parse(gh(...args));
}

function* walkDir(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) yield* walkDir(full);
    else if (entry.isFile()) yield full;
  }
}

// ── Main ──────────────────────────────────────────────────────────────────────

function main() {
  const repoRoot = git('rev-parse', '--show-toplevel');
  const localDir = path.join(repoRoot, 'docs', 'typst-packages');

  // 1. Fetch upstream recursive tree
  const tree = ghJson('api', `repos/${UPSTREAM_REPO}/git/trees/main?recursive=1`);
  const upstreamFiles = {};
  for (const entry of tree.tree) {
    if (entry.type === 'blob' &&
      (entry.path.startsWith('docs/') || entry.path === 'LICENSE')) {
      upstreamFiles[entry.path] = entry.sha;
    }
  }

  // 2. Compute local blob SHAs for existing mirror files
  const localShas = {};
  if (existsSync(localDir)) {
    for (const absPath of walkDir(localDir)) {
      const rel = path.relative(localDir, absPath).split(path.sep).join('/');
      const sha = execFileSync('git', ['hash-object', absPath], { encoding: 'utf8' }).trim();
      localShas[rel] = sha;
    }
  }

  // 3. Identify changed (new or modified) files
  const changed = Object.entries(upstreamFiles).filter(([p, sha]) => localShas[p] !== sha);

  if (changed.length === 0) {
    console.log('docs/typst-packages/ is already in sync with upstream.');
    return;
  }

  console.log(`${changed.length} file(s) changed upstream:`);
  for (const [p] of changed) {
    const status = localShas[p] ? 'modified' : 'new';
    console.log(`  [${status}] ${p}`);
  }

  // 4. Fetch and write changed files
  for (const [upstreamPath] of changed) {
    const contentData = ghJson('api', `repos/${UPSTREAM_REPO}/contents/${upstreamPath}`);
    // GitHub base64 response includes newlines for large files
    const content = Buffer.from(contentData.content.replace(/\n/g, ''), 'base64');
    const localPath = path.join(localDir, upstreamPath);
    mkdirSync(path.dirname(localPath), { recursive: true });
    writeFileSync(localPath, content);
    console.log(`  Written: ${path.relative(repoRoot, localPath)}`);
  }

  // 5. Check for an existing open PR
  let existingPr = '';
  try {
    const prs = ghJson(
      'api',
      `repos/${THIS_REPO}/pulls?head=chaoticgoodcomputing:${PR_BRANCH}&state=open`,
    );
    if (prs.length) existingPr = prs[0].html_url;
  } catch { /* no open PR */ }

  // 6. Commit and push the sync branch
  process.chdir(repoRoot);
  git('config', 'user.email', 'github-actions[bot]@users.noreply.github.com');
  git('config', 'user.name', 'github-actions[bot]');
  git('checkout', '-B', PR_BRANCH, 'origin/main');
  git('add', 'docs/typst-packages/');
  git('commit', '-m', 'chore: sync upstream typst/packages docs');
  git('push', '--force-with-lease', 'origin', PR_BRANCH);

  if (existingPr) {
    console.log(`::notice::Updated existing PR: ${existingPr}`);
    return;
  }

  // 7. Open a new PR in this repo
  const changedList = changed.map(([p]) => `- \`${p}\``).sort().join('\n');
  const body = [
    '## Upstream changes detected',
    '',
    `The following file(s) changed in \`typst/packages\`:`,
    '',
    changedList,
    '',
    '---',
    '*Auto-generated by the sync-upstream-docs workflow.*',
  ].join('\n');

  spawnSync('gh', [
    'pr', 'create',
    '--title', 'chore: sync upstream typst/packages docs',
    '--body', body,
    '--head', PR_BRANCH,
    '--base', 'main',
  ], { encoding: 'utf8', stdio: 'inherit' });

  console.log('PR opened.');
}

main();
